version: "3.4"
services:
    njtransit:
        build: .
        #user: 1000:1000
        volumes:
            - .:/app:z
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
        ports:
            - 8888:8888
        command: jupyter notebook --ip=0.0.0.0 --port=8888
